### ISSUE TITLE
Select xl model files from the local ComfyUI model directory

### ISSUE THREAD

**Issue by seasnakes** [ZHO-ZHO-ZHO/ComfyUI-PhotoMaker#11]
Issue Description:

Currently, ComfyUI-photomaker only supports selecting model files from the Hugging Face hosted repository. It is necessary to add support for selecting xl model files from the local ComfyUI model directory.

Solution:

 use **PhotoMakerStableDiffusionXLPipeline.from_single_file**  to  make it possible to loading local models files

Expected Outcome:

After implementing the above solution, users will be able to select xl model files from the local ComfyUI model directory, rather than being limited to selecting from the Hugging Face hosted repository. This will provide greater flexibility and convenience, allowing users to choose model files based on their own needs.

**Comment by bmaltais** [comment]
I agree... the current implementation of PhotoMaker does not land itself to use a model loaded using the standard "Load Checkpoint"... I would be nice if this could be made to work instead of loading a diffuser UNet model...

![image](https://github.com/ZHO-ZHO-ZHO/ComfyUI-PhotoMaker/assets/7474674/d2d402b5-5e0d-469a-bc7c-56c124a4f476)

**Comment by bmaltais** [comment]
Was reading the code and apparently it can take a state dic as a model instead of a file path... so maybe if we provide a model as an input and somehow convert it to a state dict it would solve this: 

https://pytorch.org/tutorials/beginner/saving_loading_models.html#what-is-a-state-dict
